// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmg30Yjbvg3lY1ftbIw3GHSgcMEmYlA-A',
    appId: '1:928032785050:android:59f10e566156a38deb9523',
    messagingSenderId: '928032785050',
    projectId: 'com-app-treino',
    storageBucket: 'com-app-treino.firebasestorage.app',
  );
  static const FirebaseOptions web = FirebaseOptions(
      apiKey: "AIzaSyCS-8nrdrO4T7Hg7yJ8eMhTqdXWYZjIuNs",
      authDomain: "com-app-treino.firebaseapp.com",
      projectId: "com-app-treino",
      storageBucket: "com-app-treino.firebasestorage.app",
      messagingSenderId: "928032785050",
      appId: "1:928032785050:web:958bbafb8c737e5deb9523");

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZwBQHj2ZMPf4wVbjlNpunRKDkZj3CBVw',
    appId: '1:928032785050:ios:ca86df22eaa0a3fceb9523',
    messagingSenderId: '928032785050',
    projectId: 'com-app-treino',
    storageBucket: 'com-app-treino.firebasestorage.app',
    iosBundleId: 'com.example.appTenda',
  );
}