workflows:
  android-workflow:
    name: Android Dev & Prod
    max_build_duration: 60
    instance_type: mac_mini_m2
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: develop
          include: true
          source: true
        - pattern: main
          include: true
          source: true
    environment:
      groups:
        - android_credentials
      flutter: stable
      xcode: latest
      java: 17
    scripts:
      - name: Set up local.properties
        script: |
          echo "flutter.sdk=$HOME/programs/flutter" > "$CM_BUILD_DIR/android/local.properties"
      
      - name: Set up key.properties
        script: |
          echo "storePassword=$CM_STORE_PASSWORD" > "$CM_BUILD_DIR/android/key.properties"
          echo "keyPassword=$CM_KEY_PASSWORD" >> "$CM_BUILD_DIR/android/key.properties"
          echo "keyAlias=$CM_KEY_ALIAS" >> "$CM_BUILD_DIR/android/key.properties"
          echo "storeFile=keystore.jks" >> "$CM_BUILD_DIR/android/key.properties"
          
          # Decodifica o keystore da variável de ambiente CM_KEYSTORE (base64)
          echo "$CM_KEYSTORE" | base64 --decode > "$CM_BUILD_DIR/android/keystore.jks"

      - name: Create .env file
        script: | 
          echo "GEMINI_API_KEY=$GEMINI_API_KEY" > "$CM_BUILD_DIR/.env"

      - name: Create .env file
        script: | 
          echo "GEMINI_API_KEY=$GEMINI_API_KEY" > "$CM_BUILD_DIR/.env"

      - name: Get Flutter packages
        script: |
          flutter packages pub get

      - name: Build Android App Bundle (Prod)
        script: |
          # Builda o AAB para o flavor tucttxProd
          flutter build appbundle --release --flavor tucttxProd --dart-define=TENANT=tucttx --dart-define=ENV=prod

    artifacts:
      - build/**/outputs/**/*.aab
      - build/**/outputs/**/mapping.txt
      - flutter_drive.log

    publishing:
      google_play:
        # Usa as credenciais JSON da variável de ambiente
        credentials: $GCLOUD_SERVICE_ACCOUNT_CREDENTIALS
        track: internal
        submit_as_draft: true


