# Uncomment this line to define a global platform for your project
platform :ios, '15.0'

# CocoaPods analytics sends network stats synchronously affecting flutter build latency.
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
  'Debug-tucttxDev' => :debug,
  'Debug-tucttxProd' => :debug,
  'Release-tucttxDev' => :release,
  'Release-tucttxProd' => :release,
  'Debug-tu7eDev' => :debug,
  'Debug-tu7eProd' => :debug,
  'Release-tu7eDev' => :release,
  'Release-tu7eProd' => :release,
  'Debug-tusvaDev' => :debug,
  'Debug-tusvaProd' => :debug,
  'Release-tusvaDev' => :release,
  'Release-tusvaProd' => :release,
}

def flutter_root
  generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'Generated.xcconfig'), __FILE__)
  unless File.exist?(generated_xcode_build_settings_path)
    raise "#{generated_xcode_build_settings_path} must exist. If you're running pod install manually, make sure flutter pub get is executed first"
  end

  File.foreach(generated_xcode_build_settings_path) do |line|
    matches = line.match(/FLUTTER_ROOT\=(.*)/)
    return matches[1].strip if matches
  end
  raise "FLUTTER_ROOT not found in #{generated_xcode_build_settings_path}. Try deleting Generated.xcconfig, then run flutter pub get"
end

require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)

flutter_ios_podfile_setup

target 'Runner' do
  use_frameworks!

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
  target 'RunnerTests' do
    inherit! :search_paths
  end
end


post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.0'
      config.build_settings['DEBUG_INFORMATION_FORMAT'] = 'dwarf-with-dsym'
      config.build_settings['ENABLE_BITCODE'] = 'NO'
      config.build_settings['STRIP_INSTALLED_PRODUCT'] = 'NO'
      config.build_settings['COPY_PHASE_STRIP'] = 'NO'
    end
  end

  # Inject "Strip Objective-C" build phase into Runner
  require 'xcodeproj'
  project_path = 'Runner.xcodeproj'
  project = Xcodeproj::Project.open(project_path)
  runner_target = project.targets.find { |t| t.name == 'Runner' }
  
  script_name = '[Fix] Strip Objective-C Framework'
  script_path = '${SRCROOT}/scripts/strip_objective_c.sh'
  
  # Avoid adding duplicate phase
  unless runner_target.shell_script_build_phases.any? { |bp| bp.name == script_name }
    phase = runner_target.new_shell_script_build_phase(script_name)
    phase.shell_script = "\"#{script_path}\""
    # Ensure it runs after embedding frameworks (usually near the end)
    runner_target.build_phases.move(phase, runner_target.build_phases.count - 1)
    project.save()
  end
end


